# generated by Buildyard, do not edit. Sets FIND_REQUIRED_FAILED to the
# list of missing projects. Used by Superproject.cmake
set(FIND_REQUIRED_FAILED)
<<<<<<< HEAD
find_package(Boost 1.41.0 COMPONENTS regex serialization filesystem system QUIET)
if(NOT Boost_FOUND AND NOT BOOST_FOUND)
  set(FIND_REQUIRED_FAILED "${FIND_REQUIRED_FAILED} Boost")
endif()
if(FIND_REQUIRED_FAILED)
  set(FOUND_REQUIRED FALSE)
else()
  set(FOUND_REQUIRED TRUE)
endif()
=======
find_package(Boost 1.41.0 COMPONENTS regex serialization filesystem system thread REQUIRED)
>>>>>>> 29f4257... PersistentMap: untested SKV backend
